version: '3'

services:

  app:
    container_name: kamon_app_server
    image: golang:1.21-bullseye  
    volumes:
    - ./app:/usr/local/go/src/app
    working_dir: /usr/local/go/src/app
    environment:
    - POSTGRES_DB=${DB_DATABASE}
    - POSTGRES_USER=${DB_USER}
    - POSTGRES_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    stdin_open: true
    tty: true  

  db:
    container_name: kamon_app_db
    build: 
      context: .
      dockerfile: ./db/Dockerfile
    ports: 
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      - LANG=ja_JP.utf8
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      